attn_implementation: flash_attention_2
beta: 0.5
bf16: true
dataset_mixer:
./data/preference_pair.jsonl
  : 1.0
dataset_splits:
- train
do_eval: false
gradient_accumulation_steps: 8
gradient_checkpointing: true
gradient_checkpointing_kwargs:
  use_reentrant: false
learning_rate: 1.0e-07
log_level: info
logging_steps: 1
loss_type: pcpo
lr_scheduler_type: cosine
max_length: 2048
max_prompt_length: 1800
model_name_or_path: ./models/Llama-3-8b-Instruct
num_train_epochs: 6
optim: adamw_torch
output_dir: ./runs/M1_Llama3_8B_Instruct_pcpo
per_device_eval_batch_size: 4
per_device_train_batch_size: 2
preprocessing_num_workers: 8
prompt_type: llama3_math
push_to_hub: false
remove_unused_columns: false
rpo_alpha: 1
save_steps: 0.5
save_strategy: steps
save_total_limit: 1
seed: 3407
torch_dtype: null
warmup_ratio: 0.1
